FROM ubuntu:15.10
RUN apt-get -y update
RUN apt-get -y install curl
RUN apt-get -y install git pkg-config
RUN apt-get -y install python3
RUN apt-get -y install wget
RUN apt-get -y install build-essential libmagickwand-dev libopencv-dev
